module Apohllo
  module Cyc
    class Mapping
      MAPPING_GENL = {
        :Intangible => :AbstractObj,
        :BiologicalLivingObject => :Animal,
        :"Artifact-Generic" => :Artifact,
        :OrganismPart => :BodyPart,
        :Event => :Event,
        :EdibleStuff => :Food,
        :Person => :Human,
        :PhysicalDevice => :Instrument,
        :GeographicalRegion => :Location,
        :Place => :Location,
        :ConstructionArtifact => :Location,
        :NaturalTangibleStuff => :NaturalObj,
        :OrganicMaterial => :NaturalObj,
        :InorganicMaterial => :NaturalObj,
        :PartiallyTangible => :PhysObj,
        :Plant => :Plant,
        :Fungus => :Plant,
        :Group => :Set,
        :Situation => :State,
        :Quantity => :State,
        :System => :Structure,
        :AbstractStructure => :Structure,
        :TimeInterval => :Time
      }

      MAPPING_ISA = {
        :UnitOfMeasure => :Meter,
        :NumericInterval => :Number,
        :UnitOfTime => :Time,
        :Individual => :Proper,
        :ChemicalCompoundTypeByChemicalSpecies => :NaturalObj,
        :PartiallyTangibleTypeByPhysicalStructuralFeature => :NaturalObj,
        :ArtifactTypeByGenericCategory => :Artifact,
        # TODO 
        :Odor => :XXX
      }

      MAPPING_HIER = Hash.new([]).merge({
        :PhysObj => [:Food, :Human, :BodyPart, :Plant, :Animal, :Instrument, :Location,
          :Structure, :NaturalObj, :Artifact],
        :AbstractObj => [:Meter, :Number, :Time, :Structure, :Set, :Event, :State],
        :NaturalObj => [:Food, :Human, :BodyPart, :Plant, :Animal, :Instrument, :Location],
        :Set => [:Structure],
        :Structure => [:Animal, :Plant, :Human, :BodyPart, :Artifact],
        :Artifact => [:Instrument, :Location, :Food, :Animal, :BodyPart, :Plant, :Human],
        :Animal => [:BodyPart, :Human],
        :State => [:Event],
        :Meter => [:Time]
#        :Location => [],
#        :Number => [],
#        :Food => [],
#        :Event => [],
#        :Instrument => [],
#        :Human => [],
#        :BodyPart => [],
#        :Plant => [],
#        :Proper => [],
#        :Time => [],
      })

      # default priority is 0 
      MAPPING_PRIOR = Hash.new(0).merge({
        :"Artifact-Generic" => 1,
        :ArtifactTypeByGenericCategory => 1,
        :Intangible => 2,
        :BiologicalLivingObject => 1,
        :NaturalTangibleStuff => 2,
        :OrganicMaterial => 2,
        :ChemicalCompoundTypeByChemicalSpecies => 2,
        :PartiallyTangibleTypeByPhysicalStructuralFeature => 2,
        :PartiallyTangible => 3,
        :Place => 1,
        :Situation => 1,
        :System => 2,
        :UnitOfMeasure => 1,
      })

      MAPPING_DOMAINS = Hash.new([]).merge({
        :BodyPart => [/Bot/, /Anat/, /Ecol/, /Zool/, /Biol/, /Med/],
        :Animal => [/Zool/, /Fishg/, /Agric/, /Vet/],
        :Plant => [/Bot/, /Agric/,/Hort/],
        :Food => [/Culin/],
        :AbstractObj => [/Literat/, /Theat/, /Cin/, /Art/, /Phot/, 
          /Ling/, /Math/, /Comput/, /Publg/, /Econ/, /Journ/, /Jur/,
          /Philos/, /Fin/, /Pol/, /Mus/],
        :Instrument => [/Naut/, /Mil/,/Transp/,/Constr/,/Sport/,/Aviat/,/Rail/,
          /Fishg/, /Elec/, /Aut/, /Tech/, /Mech/, /Culin/, /Comput/, /Med/,
          /Equest/, /Telecom/, /Mus/, /Nucl/, /Dent/, /Audio/,/Civ Eng/,
          /Hort/, /Hunt/, /Ind/, /Phot/, /Radio/, /Cin/],
        :NaturalObj => [/Miner/, /Geog/, /Bot/, /Meteorol/, /Geol/,
          /Chem/, /Phys/, /Zool/, /Med/, /Culin/],
        :Artifact => [/Naut/, /Mil/,/Transp/,/Constr/,/Sport/,/Aviat/,/Rail/,
          /Fishg/, /Elec/, /Aut/, /Tech/, /Mech/, /Culin/, /Comput/, /Med/,
          /Equest/, /Telecom/, /Mus/, /Nucl/, /Dent/, /Audio/,/Civ Eng/,
          /Hort/, /Hunt/, /Ind/, /Phot/, /Radio/, /Cin/],
        :Structure => [/Jur/, /Fin/,/Mil/,/Admin/, /Comm/, /Ind/,
          /Pol/, /Relig/, /Sociol/, /Ling/,/Comput/],
        :Location => [/Agric/, /Geog/, /Geol/, /Ecol/, /Admin/, 
          /Pol/, /Archeol/, /Transp/, /Rail/, /Post/, /Meteorol/,
          /Constr/, /Archit/, /Mining/],
        :Meter => [/Elec/, /Phys/, /Meas/, /Math/, /Meteorol/, 
          /Chem/, /Comput/, /Astron/, /Fin/],
        :Time => [/Meas/,/Astron/, /Geol/, /Math/, /Hist/, /Fin/],
        :Human => [/Mil/, /Pol/, /Sport/, /Relig/, /Sch/, /Univ/,
          /Aviat/, /Med/, /Admin/, /Comm/, /Theat/, /Cin/, /Mus/,
          /Jur/, /Radio/, /Fin/, /Turf/, /TV/, /Psych/] 
      })

      MAPPING_PARADIGMATIC = Hash.new([]).merge({
        :BodyPart => [:OrganismPart, :"Vegetable-Plant"],
        :Animal => [:NonHumanAnimal],
        :AbstractObj => [:Intangible],
        :Plant => [:Fungus, :Plant],
        :Food => [:EdibleStuff],
        :Instrument => [:PhysicalDevice]
      })

      MAPPING_SYNTAGMATIC = Hash.new([]).merge({
        :BodyPart => [:BiologicalLivingObject],
        :AbstractObj => [:Intangible],
        :Artifact => [:PhysicalDevice, :Person],
        :Instrument => [:PhysicalDevice, :Person, :OrganismPart, :Event],
        :Location => [:GeographicalRegion, :ConstructionArtifact],
        :Human => [:Group, :Event]
      })
      
      COLORS = [:yellow, :blue, :lightblue, :purple, :white]

      STOP_TERMS = [:Thing, :Collection, :UnitOfMeasureNoPrefix, 
        :UnitOfMeasureConcept, :TwoDimensionalUnitOfMeasure, 
        :MultiDimensionalUnitOfMeasure, :UniversalUnitOfMeasure, 
        :"OtherUnitOfMeasureInstances-Quantity-Topic", 
        :"UniversalUnitOfMeasure-Common", :"InternationalUnitOfMeasure-Common", 
        :UnitOfMeasureWithPrefix, :"USUnitOfMeasure-Common", 
        :"TimeAsAQuantity-Time-Topic", :"MKSUnitOfMeasure-Base",
        :"SIUnitOfMeasure-Base", :"Comparisons-Quantity-Topic",
        :MKSUnitOfMeasure, :MetricUnitOfMeasure, :SIUnitOfMeasure,
        :"Agent-PartiallyTangible", :PurposefulPhysicalAction, 
        :TKBCountryList, :PersonWithNationality, :SomethingExisting,
        :"Artifact-NonAgentive", :HumanlyOccupiedSpatialObject, 
        :TemporalThing, :ReflexiveBinaryPredicate, :IndividualLevelPredicate,
        :UnderspecifiedPredicate, ] +  
        MAPPING_GENL.keys + MAPPING_ISA.keys - 
        [:GeographicalRegion, :OrganicMaterial, :InorganicMaterial, 
          :Fungus, :ChemicalCompoundTypeByChemicalSpecies]

      ISA_CATEGORIES = [:Proper, :Meter, :Number, :Time]

      SEPARATION_LEN = 20

      TOPICS = {
        "Accts" => [],
        "Admin" => [ 
          :"governmentorganizations-organization-topic",
              ],
        "Advertg" => [],
        "Aerosp" => [],
        "Agric" => [],
        "Anat" => [ 
          :"animalbodypartsystems-physiology-topic",
          :"generalanimalanatomy-physiology-topic",
          :"specificanimalbodyparts-physiology-topic",
              ],
        "Anthrop" => [],
        "Antiq" => [],
        "Archeol" => [],
        "Archit" => [],
        "Art" => [ 
          :"ArtsAndLiterature-Topic",
          :"Entertainment-Topic",
              ],
        "Astrol" => [],
        "Astron" => [ 
          :"CelestialEvents-Time-Topic",
              ],
        "Audio" => [],
        "Aut" => [],
        "Aviat" => [],
        "Bible" => [],
        "Biol" => [ 
          :"BiologicalEvents-Biology-Topic",
          :"BiologicalKinRelationships-Biology-Topic",
          :"Biology-Topic",
          :"OrganismByHabitat-Biology-Topic",
          :"OrganismBySourceOfNutrients-Biology-Topic",
          :"OrganismByTaxonomicKingdom-Biology-Topic",
          :"OrganismParts-Biology-Topic",
          :"PlantsByBotanicalTaxonomy-Biology-Topic",
          :"PlantsByGrossForm-Biology-Topic",
          :"PlantsBySeasonalChange-Biology-Topic",
              ],
        "Bot" => [],
        "Chem" => [ 
          :"ChemicalCompoundsMolecules-Chemistry-Topic",
          :"ChemicalReactions-Chemistry-Topic",
          :"Chemistry-Topic",
          :"ElementsAndAtoms-Chemistry-Topic",
          :"Purity-Chemistry-Topic",
          :"Metal-Chemistry-Topic",
          :"Sub-AtomicParticles-Chemistry-Topic",
          :"SomePhysicalProperties-Chemistry-Topic",
              ],
        "Cin" => [],
        "Civ Eng" => [],
        "Comm" => [ 
          :"CommercialActivities-Financial-Topic",
          :"CommercialOrganizationsAndAccounts-Financial-Topic",
              ],
        "Comput" => [ 
          :"Computers-Topic",
          :"DistributedAI-Topic",
          :"ArtificialIntelligence-Topic",
              ],
        "Constr" => [ 
          :"Construction-Topic",
              ],
        "Cosmet" => [],
        "Culin" => [ 
          :"ConsumingFood-Food-Topic",
          :"EdiblesInGeneral-Food-Topic",
          :"FoodAndDrink-Topic",
          :"Foodstuffs-Food-Topic",
          :"Food-Topic",
          :"HungerAndMalnutrition-Food-Topic",
          :"PreparingFood-Food-Topic",
              ],
        "Dance" => [],
        "Dent" => [],
        "Ecol" => [],
        "Econ" => [],
        "Educ" => [],
        "Elec" => [ 
          :"ElectricalConductivity-Material-Topic",
              ],
        "Electron" => [],
        "Equest" => [],
        "Fashn" => [ 
          :"Clothing-Topic",
              ],
        "Fin" => [ 
          :"ProductsAndMarketing-Financial-Topic",
          :"MoneyAndCommerce-Topic",
          :"MoneyAndIncome-Financial-Topic",
          :"Financial-Topic",
          :"MoneyAndPrice-PossTransfer-Topic",
          :"MoneyTransfer-PossTransfer-Topic",
              ],
        "Fishg" => [],
        "Games" => [],
        "Geog" => [ 
          :"Addresses-Geography-Topic",
          :"Geography-Topic",
          :"GeopoliticalEntities-Geography-Topic",
          :"GeopoliticalEntities-Individuals-Geography-Topic",
          :"Miscellaneous-Geography-Topic",
          :"PoliticsAndGovernment-Geography-Topic",
          :"SomeCountries-Geography-Topic",
          :"SomeImportantRegions-Geography-Topic",
          :"UnitedStates-Geography-Topic",
              ],
        "Geol" => [],
        "Herald" => [],
        "Hist" => [ 
          :"History-Topic",
              ],
        "Hort" => [],
        "Hunt" => [],
        "Ind" => [],
        "Insur" => [],
        "Journ" => [],
        "Jur" => [ 
          :"SomeSampleKindsOfAgreements-Agreement-Topic",
          :"PredicatesDescribingAgreements-Agreement-Topic",
          :"MakingAndEndingAgreements-Agreement-Topic",
              ],
        "Ling" => [ 
          :"SomeExamplePartsOfSpeech-Linguistic-Topic",
          :"NaturalLanguageParsing-Topic",
          :"NaturalLanguageProcessing-Topic",
          :"ExamplesOfPredicatesIndicatingSyntacticPropertiesOf-Linguistic-Topic",
          :"Lexicon-Topic",
          :"Linguistic-Topic",
          :"PredicatesLinkingWordUnitsToStrings-Lexicon-Topic",
              ],
        "Literat" => [],
        "Math" => [ 
          :"ArithmeticFunctions-Math-Topic",
          :"LogicAndMath-Topic",
          :"Main-Math-Topic",
          :"Math-Topic",
          :"Numbers-Math-Topic",
          :"Predicates-Math-Topic",
          :"RelationalStructures-Math-Topic",
          :"SubsetsOfComputationalObject-Math-Topic",
          :"SubsetsOfMathematicalThing-Math-Topic",
          :"Vectors-Math-Topic",
              ],
        "Mech" => [ 
              ],
        "Med" => [ 
          :"Ailments-Topic",
          :"GeneralMedicine-Topic",
          :"Healthcare-Topic",
          :"MedicalCareEvents-GeneralMedicine-Topic",
          :"MedicalCareProviders-GeneralMedicine-Topic",
          :"MedicallyRelevantConditionTypes-GeneralMedicine-Topic",
          :"Medical-Topic",
          :"Medicine-Other-Topic",
              ],
        "Meas" => [ 
          :"MeasurementOfWavePhenomena-Wave-Topic",
          :"ClimaticSeasons-Time-Topic",
              ],
        "Meteorol" => [ 
          :"WeatherAttributes-Weather-Topic",
          :"WeatherEvents-Weather-Topic",
          :"WeatherObjects-Weather-Topic",
          :"Weather-Topic",
          :"ClimateCycles-Weather-Topic",
          :"ClimaticSeasons-Weather-Topic",
              ],
        "Mgmt" => [ 
          :"ExamplesOfLocalOrganizations-Organization-Topic",
          :"EventsAboutChangesOfOrganizationMembership-Organization-Topic",
          :"CustomerRelationsWithOrganizations-Organization-Topic",
          :"MiscellaneousOrganizationConstants-Organization-Topic",
          :"OccupationsByTypeOfEmployingOrganization-Professional-Topic",
          :"OrganizationsByBusinessProfitNature-Organization-Topic",
          :"OrganizationsByFunction-Organization-Topic",
          :"OrganizationsByGeographicalScope-Organization-Topic",
          :"OrganizationsByLegalForm-Organization-Topic",
          :"OrganizationsRelatedToProductsOrServices-Organization-Topic",
          :"Organization-Topic",
          :"PartsOfOrganizations-Organization-Topic",
          :"PeopleRelatedToOrganizations-Organization-Topic",
          :"RelationshipsAmongOrganizations-Organization-Topic",
              ],
        "Mil" => [ 
          :"GenericMilitaryOrganizations-Organization-Topic",
              ],
        "Mil Naut" => [],
        "Miner" => [],
        "Mining" => [],
        "Mus" => [],
        "Mythol" => [],
        "Naut" => [],
        "Nucl" => [  ],
        "Pharm" => [],
        "Philos" => [],
        "Phon" => [],
        "Phot" => [],
        "Phys" => [ 
          :"PhysicalStuffAndObjects-Topic",
          :"PhysicalTransportPathTypes-PathTraversal-Topic",
          :"Physics-Topic",
          :"ThermalConductivity-Material-Topic",
          :"StatesOfMatter-Material-Topic",
          :"StructuralAttributes-Material-Topic",
              ],
        "Physiol" => [ 
          :"BodyPositionAndMovement-Physiology-Topic",
          :"Physiology-Topic",
          :"SpecificPhysiologicalProcesses-Physiology-Topic",
          :"Sensors-Perception-Topic",
          :"SensoryReactionsAndAttributesAndUrges-Perception-Topic",
          :"SimilarityInAttributes-Perception-Topic",
          :"Perception-Topic",
              ],
        "Pol" => [],
        "Post" => [],
        "Print" => [],
        "Psych" => [ 
          :"Goals-Attitude-Topic",
          :"Expectation-Attitude-Topic",
          :"Emotion-Topic",
          :"Desires-Attitude-Topic",
          :"AffectPredicates-Emotion-Topic",
          :"Attitude-Topic",
          :"PredicatesForTalkingAboutLikingAndDisliking-Emotion-Topic",
          :"SomeEmotionsAboutAnothersSuccess-Emotion-Topic",
          :"SomeEmotionsAboutArousal-Emotion-Topic",
          :"SomeEmotionsAboutAttractionAndDislike-Emotion-Topic",
          :"SomeEmotionsAboutExpectations-Emotion-Topic",
          :"SomeEmotionsAboutThePresent-Emotion-Topic",
          :"SomeEmotionsAboutTheRealizationOfExpectations-Emotion-Topic",
          :"SomeExampleFeelingAttributeTypes-Emotion-Topic",
          :"SomeOther-AttributionEmotions-Emotion-Topic",
          :"SomeSelf-AttributionEmotions-Emotion-Topic",
          :"TopLevelAffectCollections-Emotion-Topic",
              ],
        "Publg" => [],
        "Radio" => [],
        "Rail" => [],
        "Relig" => [ 
          :"Beliefs-Attitude-Topic",
              ],
        "Sch" => [ 
          :"Education-Social-Topic",
          :"Education-Topic",
              ],
        "Sci" => [ 
          :"ScienceAndNature-Topic",
              ],
        "Sewing" => [],
        "Sociol" => [ 
          :"Competition-Social-Topic",
          :"GeneralSocialConstants-Social-Topic",
          :"Interests-Social-Topic",
          :"LifeStages-Social-Topic",
          :"PopulationClassificationTerms-Social-Topic",
          :"Relationships-Social-Topic",
          :"Residence-Social-Topic",
          :"SocialClass-Social-Topic",
          :"SocialEvents-Social-Topic",
          :"Social-Topic",
          :"SomeSampleKindsOfSocialActions-Social-Topic",
          :"TitlesAndNames-Social-Topic",
              ],
        "Sport" => [ 
          :"SportsAndLeisure-Topic",
              ],
        "Stat" => [],
        "Tax" => [ 
          :"FiscalCycles-Time-Topic",
              ],
        "Tech" => [ 
          :"States-Device-Topic",
          :"SpecializationsOfPhysicalDevice-Device-Topic",
          :"Solubility-Material-Topic",
          :"Predicates-Device-Topic",
          :"Material-Topic",
          :"GenericCollectionsForMaterials-Material-Topic",
          :"CommonSubstances-Material-Topic",
          :"AttributesOfMaterials-Material-Topic",
          :"Action-Device-Topic",
          :"Artifacts-Topic",
          :"Devices-Topic",
              ],
        "Telcom" => [ 
          :"Communication-Topic",
              ],
        "Time" => [ 
          :"ThingsWithTemporalExtent-Time-Topic",
          :"TimeAsAQuantity-Time-Topic",
          :"TimeOfDay-Time-Topic",
          :"TimePoints-Time-Topic",
          :"Time-RelatedPredicateTypes-Time-Topic",
          :"Time-Topic",
          :"TheCalendar-Time-Topic",
          :"RepeatedEvents-Time-Topic",
          :"RelationsBetweenTemporalObjects-Time-Topic",
          :"PropertiesOfTemporalObjects-Time-Topic",
          :"OtherTime-RelatedConstants-Time-Topic",
          :"DisjointTemporalObjects-Time-Topic",
          :"Type-LevelTemporalRelations-Time-Topic",
              ],
        "Tex" => [],
        "Theat" => [],
        "Tourism" => [],
        "Transp" => [ 
          :"Transportation-Topic",
              ],
        "Turf" => [],
        "TV" => [],
        "Univ" => [ 
          :"Knowledge-Attitude-Topic",
          :"KnowledgeFormationAndDialog-Topic",
          :"AcademicCycles-Time-Topic",
          :"FieldsOfKnowledge-Social-Topic",
              ],
        "Vet" => [],
        "Wine" => [],
        "Zool" => [ 
          :"AnimalBySex-Biology-Topic",
          :"AnimalByStageOfDevelopment-Biology-Topic",
          :"AnimalByTaxonomicPhylumWithSamples-Biology-Topic",
          :"AnimalsByGrossForm-Biology-Topic",
          :"AnimalsByMiscellaneousCriteria-Biology-Topic",
          :"AnimalPhysiology-Physiology-Topic",
          :"SomeSampleKindsOfAmphibian-Biology-Topic",
          :"SomeSampleKindsOfBird-Biology-Topic",
          :"SomeSampleKindsOfMammal-Biology-Topic",
          :"SomeSampleKindsOfReptile-Biology-Topic",
          :"VertebratesByTaxonomicClass-Biology-Topic",
          ]
      }

    end # Mapping
    class Cyc
      IRRELEVANT_MTS = [:WordNetMappingMt, :EnglishMt, :UniversalVocabularyMt, 
        :BaseKB, :CycHistoricalPossibilityTheoryMt, :SENSUSMappingMt, 
        :GeneralLexiconMt, :BookkeepingMt,  :CycNounLearnerMt, :HPKBVocabMt,
        :SKSIMt, :TopicMt, :SNOMEDMappingMt, :MeSHMappingMt, :CycNounLearnerMt,
        :TheMotleyFoolUKCorpusMt, :AnalystDatabaseMt, :CyclistsMt ]
    end
  end
end
